In [ ]:
#Name: Aashish Singh , Section: Q , Roll No.: 20

In [ ]:
"""
Problem Statement: 13  
Develop a program to implement the K-Nearest Neighbours (KNN) 
algorithm on a given dataset related to student performance with 
target as Result(student_performance.csv). The program should 
perform the following tasks: 
i. Read the given dataset into a dataframe. 
ii. Separate the input features and the target class label (Result). 
iii. Split the dataset into training and testing sets in the ratios 70:30, 
60:40, 80:20. 
iv. Implement the K-Nearest Neighbours (KNN) classification 
algorithm for a suitable value of K. 
v. Train the model using the training data and classify the test 
samples. 
vi. Evaluate the performance of the model using accuracy, precision, 
F1 score and recall and show the confusion matrix. 
vii. Use the trained model to predict the class label for new data 
points. 
"""

In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [10]:
# Generate Dataset (student_performance.csv)
# -------------------------------
np.random.seed(42)

n = 100

study_hours = np.random.randint(1, 10, n)
attendance = np.random.randint(50, 100, n)
assignments = np.random.randint(1, 10, n)
previous_score = np.random.randint(40, 95, n)

# Logic for Result
result = []
for i in range(n):
    score = (
        study_hours[i] * 5 +
        attendance[i] * 0.3 +
        assignments[i] * 4 +
        previous_score[i] * 0.5
    )
    if score > 120:
        result.append("Pass")
    else:
        result.append("Fail")

data = pd.DataFrame({
    "study_hours": study_hours,
    "attendance": attendance,
    "assignments": assignments,
    "previous_score": previous_score,
    "Result": result
})

# Save CSV
data.to_csv("student_performance.csv", index=False)
print("Dataset generated successfully!\n")

Dataset generated successfully!



In [11]:
# -------------------------------
# i. Load Dataset
# -------------------------------
data = pd.read_csv("student_performance.csv")

# -------------------------------
# ii. Separate Features & Target
# -------------------------------
X = data.drop("Result", axis=1)
y = data["Result"]

# -------------------------------
# Function to train & evaluate
# -------------------------------
def run_knn(test_ratio, k):
    print(f"\n--- Split {int((1-test_ratio)*100)}:{int(test_ratio*100)} ---")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_ratio, random_state=42
    )

    model = KNeighborsClassifier(n_neighbors=k)
    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    # -------------------------------
    # vi. Metrics
    # -------------------------------
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, pos_label="Pass")
    rec = recall_score(y_test, y_pred, pos_label="Pass")
    f1 = f1_score(y_test, y_pred, pos_label="Pass")
    cm = confusion_matrix(y_test, y_pred)

    print("Accuracy:", acc)
    print("Precision:", prec)
    print("Recall:", rec)
    print("F1 Score:", f1)
    print("Confusion Matrix:\n", cm)

    return model


# -------------------------------
# iii. Different Splits
# -------------------------------
model_70 = run_knn(0.3, k=3)
model_60 = run_knn(0.4, k=3)
model_80 = run_knn(0.2, k=3)

# -------------------------------
# vii. Predict New Data
# -------------------------------
print("\nEnter new student data:")

user_vals = []
for col in X.columns:
    val = float(input(f"Enter {col}: "))
    user_vals.append(val)

user_df = pd.DataFrame([user_vals], columns=X.columns)

prediction = model_80.predict(user_df)

print("\nPredicted Result:", prediction[0])


--- Split 70:30 ---
Accuracy: 0.8
Precision: 0.5
Recall: 0.5
F1 Score: 0.5
Confusion Matrix:
 [[21  3]
 [ 3  3]]

--- Split 60:40 ---
Accuracy: 0.825
Precision: 0.5
Recall: 0.5714285714285714
F1 Score: 0.5333333333333333
Confusion Matrix:
 [[29  4]
 [ 3  4]]

--- Split 80:20 ---
Accuracy: 0.75
Precision: 0.25
Recall: 0.3333333333333333
F1 Score: 0.2857142857142857
Confusion Matrix:
 [[14  3]
 [ 2  1]]

Enter new student data:


Enter study_hours:  4
Enter attendance:  60
Enter assignments:  6
Enter previous_score:  85



Predicted Result: Fail
